version: "2"
services:
    db:
        container_name: mariadb
        hostname: mariadb
        image: mariadb
        ports:
          - "3306:3306"
        environment:
          MYSQL_DATABASE: testDB
          MYSQL_USER: yuby
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
        volumes:
          - persistent:/var/lib/mysql
          - ./files:/files
        networks:
          - default
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        hostname: pma
        links:
          - db:db
        ports:
          - 8000:80
        environment:
          MYSQL_USER: yuby
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: secret
volumes:
    persistent:
